server:
  proxy:
    hostport: 127.0.0.1:5433
  admin:
    hostport: 127.0.0.1:8000

nodes:
  master:
    # hostport: 172.19.13.165:5432
    hostport: 172.19.2.154:5432
    role: master
    metadata: {}
  replica1:
    # hostport: 172.19.13.78:5432
    hostport: 172.19.2.155:5432
    role: replica
    metadata: {}

credentials:
  username: postgres
  database: postgres
  password: 123456
  options:
  ssl:
    enable: false
    sslmode: disable

pool:
  capacity: 2

healthcheck:
  delay: 60
  query: select now();

forceparse: false
